spring.application.name=AiAgent

# ================================
# GROQ - CHAT uniquement
# ================================
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.chat.options.stream=false
spring.ai.openai.chat.options.stream-usage=false
spring.ai.openai.chat.options.max-tokens=500
spring.ai.openai.embedding.enabled=false

# ================================
# H2 DATABASE (fichier persistant)
# ================================
spring.datasource.url=jdbc:h2:file:./data/aiagent-db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

# ================================
# UPLOAD FICHIERS
# ================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ================================
# SERVER
# ================================
server.port=8080
spring.web.resources.add-mappings=false
spring.ai.retry.max-attempts=1
